### ISSUE TITLE
0.3.1 unhandled error event

### ISSUE THREAD

**Issue by ilanbiala** [SBoudrias/gulp-istanbul#41]
My task:

```
gulp.task('mocha', ['env:test'], function() {
    var mongoose = require('./config/mongoose');


    gulp.src(['app/**/*.js', 'config/**/*.js', 'public/**/*.js'])
        .pipe(istanbul())
        .on('finish', function() {

            mongoose
                .connect()
                .then(function(db) {
                    return gulp.src('./test/**/*.js')
                        .pipe(mocha({}))
                        .pipe(istanbul.writeReports())
                        .once('end', function() {
                            mongoose.disconnect();
                        });

                });
        });
});
```

Error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Line 46: Unexpected token ;
    at throwError (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:1831:21)
    at throwUnexpected (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:1889:9)
    at expect (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:1898:13)
    at parseGroupExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2139:9)
    at parsePrimaryExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2151:20)
    at parseLeftHandSideExpressionAllowCall (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2275:61)
    at parsePostfixExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2325:16)
    at parseUnaryExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2384:20)
    at parseBinaryExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2473:16)
    at parseConditionalExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2533:16)
    at parseAssignmentExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2559:23)
    at parseExpression (node_modules/gulp-istanbul/node_modules/istanbul/node_modules/esprima/esprima.js:2585:16)
```

**Comment by jsdevel** [comment]
It would be nice if coverage threshold errors were spelled out in the terminal.  I just got bit by `Unhandled 'error' event` as well.  The problem went away once I brought coverage up, but I could see many devs being confused by that.

Is there a way to be more explicit?  @SBoudrias is that something we'd need to bake into Istanbul?

**Comment by jsdevel** [comment]
I ended up doing this to display the error in the console:

```javascript
gulp.task('test', function (cb) {                                                    
  chai.should();                                                                     
                                                                                     
  gulp.src(jsServerFiles)                                                            
    .pipe(istanbul()) // Covering files                                              
    .pipe(istanbul.hookRequire()) // Force `require` to return covered files         
    .on('finish', function () {                                                      
      gulp.src(testFiles)                                                            
        .pipe(mocha())                                                               
        .pipe(istanbul.writeReports()) // Creating the reports after tests runned       
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } })) // Enforce a coverage of at least 90%
        .on('error', function(err) {                                                 
          console.log(err);                                                          
          process.exit(1);                                                           
        })                                                                           
        .on('end', cb);                                                              
    });                                                                              
});
```

**Comment by SBoudrias** [comment]
This is unfortunately the way gulp works.

Maybe it'll get fixed in a future release, but it's been like that for a while.
