### ISSUE TITLE
Coverage fail error

### ISSUE THREAD

**Issue by PaymentGeek** [SBoudrias/gulp-istanbul#72]
Hello,

While trying to produce a coverage report, I get the following failure and error

=============================== Coverage summary ===============================
Statements   : 34.12% ( 29/85 )
Branches     : 0% ( 0/10 )
Functions    : 11.11% ( 2/18 )
Lines        : 34.94% ( 29/83 )

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Coverage failed

I added a console.trace() command and here are the details:

{ [Error: Coverage failed]
  message: 'Coverage failed',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-istanbul',
  __safety: { toString: [Function] } }
Trace
    at DestroyableTransform.<anonymous> (/home/ubuntu/workspace/proxy-server/gulpfile.js:42:19)
    at DestroyableTransform.emit (events.js:117:20)
    at DestroyableTransform.<anonymous> (/home/ubuntu/workspace/proxy-server/node_modules/gulp-istanbul/index.js:156:12)
    at DestroyableTransform.emit (events.js:117:20)
    at /home/ubuntu/workspace/proxy-server/node_modules/gulp-istanbul/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickDomainCallback (node.js:486:13)

Can anyone suggest what I am missing here?

Code is:

gulp.task('test', function (cb) {
  gulp.src(['./test/endsever.1.js','./proxy.js','./lib/saveToDB.js','./test/client.1.js'])
    .pipe(istanbul()) // Covering files
    .pipe(istanbul.hookRequire()) // Force `require` to return covered files
    .on('error', function(err) {                                                 
          console.log(err);                                                          
          process.exit(1);                                                           
        })         
    .on('finish', function () {
      gulp.src(['./test/endsever.1.js','./proxy.js','./lib/saveToDB.js','./test/client.1.js'])
        .pipe(mocha())
        .pipe(istanbul.writeReports()) // Creating the reports after tests ran
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } })) // Enforce a coverage of at least 90%
        .on('error', function(err) {                                                 
          //console.log(err({showStack:true}));
          console.log(err);
          console.trace();
          process.exit(1);                                                           
        })         
        .on('end', cb);
Thanks in advance

**Comment by PaymentGeek** [comment]
The Threshold enforce statement was causing the event. Sorry :)
