### ISSUE TITLE
Doesn't Work With Gulp Watch

### ISSUE THREAD

**Issue by planetmalone** [SBoudrias/gulp-istanbul#87]
I recently added gulp-istanbul to my gulp build. I used the example in the README with mocha. 

Here are my tasks:

```javascript
gulp.task('pre-unit', function() {
    return gulp.src([
            'app/**/*.js'
        ])
        .pipe(istanbul())
        .pipe(istanbul.hookRequire());
});

gulp.task('unit', ['lint', 'pre-unit'], function() {
    return gulp.src(['test/unit/**/*.js'])
        .pipe(plumber())
        .pipe(notify({ title: 'Unit Tests', message: 'Running unit tests.', onLast: true }))
        .pipe(mocha())
        .pipe(istanbul.writeReports({
            reporters: ['text-summary', 'html'],
            reportOpts: {
                html: { dir: './coverage' }
            }
        }))
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 85 } }));
});
```

Everything works fine until I add istanbul to a task using gulp.watch. When I add a new line to a file, it gives me this error:

```Message:
    Cannot read property 'start' of undefined
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Cannot read property 'start' of undefined
    at /Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/istanbul/lib/object-utils.js:59:44
    at Array.forEach (native)
    at Object.addDerivedInfoForFile (/Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/istanbul/lib/object-utils.js:58:37)
    at Object.Collector.fileCoverageFor (/Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/istanbul/lib/collector.js:94:15)
    at /Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/istanbul/lib/report/text-summary.js:70:66
    at Array.forEach (native)
    at TextSummaryReport.Report.mix.writeReport (/Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/istanbul/lib/report/text-summary.js:69:27)
    at /Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/index.js:131:14
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (/Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/index.js:130:15)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (/Users/planetmalone/projekts/tims/Web/node_modules/gulp-istanbul/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:960:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
```

I tracked it down to the `text-summary` reporter not adding the line to the statementMap. The place it's throwing the error is this block of code in object-utils.js:
```javascript
Object.keys(statements).forEach(function (st) {
    var line = statementMap[st].start.line,
        count = statements[st],
        prevVal = lineMap[line];
     if (count === 0 && statementMap[st].skip) { count = 1; }
     if (typeof prevVal === 'undefined' || prevVal < count) {
         lineMap[line] = count;
     }
});
```
`st` is 49 while the last index in the statementMap is 48.

Is this a known issue or is there anything I need to modify in order to allow gulp-istanbul to play nicely with gulp.watch?

I know this is code inside of istanbul, but it seems to be directly related to gulp watch.

**Comment by planetmalone** [comment]
I found a solution that works for me. I created a global coverageVariable that is updated each time the watch cycle starts.

```javascript
var coverageVariable;

gulp.task('pre-unit', function() {
    coverageVariable = '$$cov_' + new Date().getTime() + '$$';

    return gulp.src([
            'app/**/*.js'
        ])
        .pipe(istanbul( { coverageVariable: coverageVariable }))
        .pipe(istanbul.hookRequire());
});

gulp.task('unit', ['lint', 'pre-unit'], function() {
    return gulp.src(['test/unit/**/*.js'])
        .pipe(plumber())
        .pipe(notify({ title: 'Unit Tests', message: 'Running unit tests.', onLast: true }))
        .pipe(mocha())
        .pipe(istanbul.writeReports({
            coverageVariable: coverageVariable,
            reporters: ['text-summary', 'html'],
            reportOpts: {
                html: { dir: './coverage' }
            }
        }))
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 85 } }));
});
```
This means each run is a new coverage analysis. It wasn't the solution I'd prefer, but it works well.

I'll close this since I found a workable solution. Please let me know if you know of a better one.

**Comment by SBoudrias** [comment]
That's pretty much the recommended way. Otherwise the coverage data are just gonna be bundle up on top of each other.

**Comment by planetmalone** [comment]
Cool! Thanks! 

Thanks for building this!
